# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Speechly < Formula
  desc ""
  homepage "https://www.speechly.com/"
  version "0.10.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/speechly/cli/releases/download/v0.10.0/speechly_0.10.0_macOS_x86_64.tar.gz"
      sha256 "a19956debdb712f3254bac33ed0c61c3cd727b76a7e4f640959de0d42c6884d2"

      def install
        bin.install "speechly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/speechly/cli/releases/download/v0.10.0/speechly_0.10.0_macOS_arm64.tar.gz"
      sha256 "b04b65bb034288ecc69480364f35f34978e206c3f8bafeb121acd41ed485fb0b"

      def install
        bin.install "speechly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/speechly/cli/releases/download/v0.10.0/speechly_0.10.0_Linux_x86_64.tar.gz"
      sha256 "5c566772c0c0c8b9f6e478b90e0f0c79d2407bf7475777db42cd866ff65e9da9"

      def install
        bin.install "speechly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/speechly/cli/releases/download/v0.10.0/speechly_0.10.0_Linux_arm64.tar.gz"
      sha256 "5c3ad5d557f3ea341041b5e03ec8224f2ddfd11eb43863b84097fdca210fd91a"

      def install
        bin.install "speechly"
      end
    end
  end
end
