# This file was generated by GoReleaser. DO NOT EDIT.
class Speechly < Formula
  desc ""
  homepage "https://www.speechly.com/"
  version "0.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/speechly/cli/releases/download/v0.0.5/speechly_0.0.5_macOS_x86_64.tar.gz"
    sha256 "b089b2cc17bce5fbc49cd31b28125f77f0e6d21b448903993995305dd075d4c4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/speechly/cli/releases/download/v0.0.5/speechly_0.0.5_Linux_x86_64.tar.gz"
      sha256 "039879f3df0fc0add3a179e4d83aebfddda902a3fb3464b8e80ec3b3f0f59fc1"
    end
  end

  def install
    bin.install "speechly"
  end
end
